# Generated by Django 5.2.4 on 2025-07-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_parent_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
